apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
  - path: '/metrics/'
    port: http
  selector:
    matchLabels:
      app: vllm